name: Check Merged PRs

on:
  workflow_call:
    inputs:
      expected-users:
        description: "Lista de usuarios esperados (separados por coma)"
        required: false
        type: string

jobs:
  check-merges:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Check who merged
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN || github.token }}
          EXPECTED_USERS: ${{ inputs.expected-users }}
        run: |
          # Separar lista por comas en array bash
          IFS=',' read -r -a USERS <<< "$EXPECTED_USERS"

          MERGED_USERS=$(gh pr list --repo ${{ github.repository }} \
            --state merged --limit 1000 --json author \
            --jq '.[].author.login' | sort -u)

          echo "=== ESTADO DE MERGES ==="
          for user in "${USERS[@]}"; do
            if echo "$MERGED_USERS" | grep -q "^${user}$"; then
              echo "User $user has merged PRs."
            else
              echo "User $user has NOT merged PRs."
            fi
          done
