name: Check Merged PRs

on:
  workflow_call:
    inputs:
      expected-users:
        description: "Lista de usuarios esperados (separados por coma)"
        required: false
        type: string

env:
  GH_TOKEN: ${{ secrets.workflows || github.token }}

jobs:
  check-merges:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Check who merged
        env:
          GH_TOKEN: ${{ env.workflows }}
        run: |
          IFS=',' read -r -a EXPECTED_USERS <<< "${{ inputs.expected-users }}"
          DEFAULT_USERS=(
            "Asier-Merino"
            "clemente-rodriguez"
            "aimar-sarachaga"
            "ibai-garcia"
            "angel-hormilla"
            "iker-gorostiaga04"
            "Asier-Merino"
            "jon-medina04"
            "iker-pazos"
            "asier-perez05"
            "iker-iglesias"
            "iker-ortiz0225"
            "jon-juanes"
            "samuel-rivera05"
            "lander-ortuzar"
            "mikel-martinez05"
            "haimar-alvarez"
            "xabier-vila"
            "oier-cadierno"
            "aritz-basarrate"
          )
          USERS=("${EXPECTED_USERS[@]:-${DEFAULT_USERS[@]}}")

          MERGED_USERS=$(gh pr list --repo ${{ github.repository }} \
            --state merged --limit 1000 --json author \
            --jq '.[].author.login' | sort -u)

          echo "=== ESTADO DE MERGES ==="
          for user in "${USERS[@]}"; do
            if echo "$MERGED_USERS" | grep -q "^${user}$"; then
              echo "✓ $user"
            else
              echo "✗ $user"
            fi
          done
